apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story-app
  template:
    metadata:
      labels:
        app: story-app
    spec:
      containers:
      - name: story
        image: psycode99/kub-volumes:2
        env:
        - name: STORY_FOLDER
          valueFrom:
            configMapKeyRef:
              name: story-env
              key: folder
        volumeMounts:
        - mountPath: /app/story
          name: story-volume
      volumes:
      - name: story-volume
        persistentVolumeClaim: 
          claimName: host-pvc
         
     
