apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
      - name: auth-container
        image: psycode99/kub-net-auth
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
     
