apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  selector:
    matchLabels:
      app: tasks-api
  template:
    metadata:
      labels:
        app: tasks-api
    spec:
      containers:
      - name: task-container
        image: psycode99/kub-net-tasks:latest
        env:
        - name: AUTH_ADDR
          value: "auth-service.default"
        - name: TASKS_FOLDER
          value: tasks
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 8000
